Update Auth.php
secure73/gemFramework pull request #2
Opened 2024-10-09 21:21 UTC by andrenalin282

added getUserRoles to compare or ask if user has x role he can do more in one method, prevent duplication of functions with more abilities

2024-10-10 15:46 UTC, secure73 requested changes
In constructor line 30 ?user_roles shall be $this->user_rules=null; 
Thank you in advance for your work and help.

2024-10-11 06:16 UTC, andrenalin282 commented
Added get user_roles to check roles and added permissions in auth and jwt token to enhance sub permissions to system

2024-10-11 06:35 UTC, andrenalin282 commented
fixed requested array to null

2024-10-27 12:06 UTC, secure73 approved these changes

2024-10-27 12:06 UTC, merged